modLoader="javafml"
loaderVersion="${loader_version_range}"
license="All Rights Reserved"
showAsResourcePack=false

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="The Lost Ages"
displayURL="https://www.curseforge.com/minecraft/mc-mods/the-lost-ages"
logoFile="forgefrontierlostages.png"
authors="CtrlAltDyleted"
displayTest="MATCH_VERSION"

description='''
The Lost Ages is an unofficial companion mod for Create: Forge Frontier. It
adds original quests, recipes, integrations, progression changes, and
compatibility features designed for use with the modpack.

The Lost Ages is an independent, unofficial companion project and is not
affiliated with, endorsed by, or maintained by the Create: Forge Frontier
developers.
'''

# Core dependencies

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="kubejs"
mandatory=true
versionRange="[2001.6.5-build.26,)"
ordering="BEFORE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="ftbquests"
mandatory=true
versionRange="[2001.4.22,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
mandatory=true
versionRange="[6.0.8,6.0.9)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create_resource_vents"
mandatory=true
versionRange="[1.3,1.4)"
ordering="BEFORE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="ae2"
mandatory=true
versionRange="[15.4.10,16.0.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="ad_astra"
mandatory=true
versionRange="[1.15.20,1.16.0)"
ordering="AFTER"
side="BOTH"

# Additional required mods

[[dependencies.${mod_id}]]
modId="appflux"
mandatory=true
versionRange="[1.20-1.3.7-forge,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="ae2netanalyser"
mandatory=true
versionRange="[1.20-1.0.6-forge,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="ae2ct"
mandatory=true
versionRange="[1.20.1-1.1.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="mob_grinding_utils"
mandatory=true
versionRange="[1.20.1-1.1.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="botanypots"
mandatory=true
versionRange="[13.0.43,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="botanytrees"
mandatory=true
versionRange="[9.0.20,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="botanypotstiers"
mandatory=true
versionRange="[6.0.1,)"
ordering="AFTER"
side="BOTH"